#INCLUDE P16F628A.INC

__CONFIG _BOREN_ON & _CP_OFF & _PWRTE_ON & _WDT_OFF & _LVP_OFF & _MCLRE_ON & _XT_OSC

#DEFINE		BANK0	BCF	STATUS,RP0
#DEFINE		BANK1	BSF	STATUS,RP0
#DEFINE		CHAVE1	PORTA,0
#DEFINE		CHAVE2	PORTA,1
#DEFINE		CHAVE3	PORTA,2
#DEFINE		LED1		PORTB,1
#DEFINE		LED2	PORTB,2
#DEFINE		SIRENE	PORTB,3

	FREQ	EQU		20H
	DL0		EQU		21H
	DL1		EQU		22H
	DL2		EQU		23H
	FLAGS	EQU		24H
	SAVE_W	EQU		25H
	SAVE_S	EQU		26H

	ORG		000H
	GOTO		INICIO

	ORG		004H
;	BTFSC	CHAVE3
;	GOTO		SHTDWN
;	GOTO		END_INT
;SHTDWN:
;	BCF		FLAGS,0
;	BCF		LED1
;	BCF		LED2
;	GOTO		END_INT
;	MOVWF	SAVE_W
;	SWAPF	STATUS,W
;	MOVWF	SAVE_S
;	BTFSC	CHAVE3
;	GOTO		SHTDWN
;	BTFSC	FLAGS,0
;	GOTO		INT_TMR
;	GOTO		END_INT
;INT_TMR:
;	MOVLW	FREQ
;	MOVWF	TMR0
;	GOTO		END_INT
;SHTDWN:
;	BCF		FLAGS,0
;	MOVLW	B'00000000'
;	MOVWF	PORTB
;	GOTO		END_INT
;END_INT:
;	SWAPF	SAVE_S,W
;	MOVWF	STATUS
;	SWAPF	SAVE_W,F
;	SWAPF	SAVE_W,W
	RETFIE
DELAY:
	MOVLW	.2
	MOVWF	DL2
LOOP_250MS:
	MOVLW	.250
	MOVWF	DL1
LOOP_1MS:
	MOVLW	.200
	MOVWF	DL0
LOOP:
	NOP
	DECFSZ	DL0,F
	GOTO		LOOP
	DECFSZ	DL1,F
	GOTO		LOOP_1MS
	DECFSZ	DL2,F
	GOTO		LOOP_250MS
	RETURN
INICIO:
	CLRF	PORTA
	CLRF	PORTB
	BANK1
	MOVLW	B'00000111'
	MOVWF	TRISA
	MOVLW	B'00000000'
	MOVWF	TRISB
	MOVLW	B'10000000'
	MOVWF	OPTION_REG
	MOVLW	B'00000000'
	MOVWF	INTCON
	BANK0
;	MOVLW	B'00000111'
;	MOVWF	CMCON
BGNNG:
	BTFSS	CHAVE2
	GOTO 	BGNNG
;	BSF		FLAGS,0
;	BSF		INTCON,T0IE
;	BSF		SIRENE
MAIN:
;	BTFSC	CHAVE3
;	GOTO		SHTDWN
	BSF		LED1
	BCF		LED2
;	MOVLW	.99
;	MOVWF	FREQ
	CALL	DELAY
;	BTFSC	CHAVE3
;	GOTO		SHTDWN
	BCF		LED1
	BSF		LED2
;	MOVLW	.199
;	MOVWF	FREQ
	CALL	DELAY
	GOTO		MAIN
;SHTDWN:
;	BCF		LED1
;	BCF		LED2
;	BTFSS	CHAVE2
;	GOTO		SHTDWN
;	GOTO		MAIN
	END

; ------------------------------------------
; IESB - Sistemas Computacionais: Hardware
; (Prova Substitutiva) Projeto Sirene
; Orientador / Avaliador:
; 	Luis Carvalho
; Alunos:
;	Leonardo Contri	/	Matricula: 1712082029
;	Nadio Dib		/	Matricula: 1322081004
;
;	Brasilia, 2 de julho de 2017
; ------------------------------------------

#INCLUDE		P16F628A.INC

; PORTB esta sendo escolhido como padrao nas
; definicoes, pois possui resistores internos em
; todos os seus pinos de I/O (RB0 a RB7)
#DEFINE		CHAVE1	PORTB,0
#DEFINE		CHAVE2	PORTB,1
#DEFINE		CHAVE3	PORTB,2
#DEFINE		SIRENE	PORTB,3
#DEFINE		FAROL	PORTB,4

	FREQ	EQU		20H
	DL0		EQU		21H
	DL1		EQU		22H
	DL2		EQU		23H
	SAVE_W	EQU		24H
	SAVE_S	EQU		25H

; Programa principal
	ORG		000H
; Inicializa com banco 1 da RAM
	BSF		STATUS,RP0
; Inicializa com PSA (4th bit) desativado
	MOVLW	B'00000000'
	MOVWF	OPTION_REG
; Inicializa com TMR0 (5th bit) desativado
	MOVLW	B'00000000'
	MOVWF	INTCON
; Retorna ao banco 0 da RAM
	BCF		STATUS,RP0
	GOTO		INICIO

; Tratamento de interrupcoes
	ORG		004H
	MOVWF	SAVE_W
	SWAPF	STATUS,W
	MOVWF	SAVE_S
	BTFSS	PORTB,CHAVE3
	GOTO		STR_INT
	GOTO		
	BTFSS	INTCON,INTF
	GOTO		INT_TMR
	BCF		INTCON,INTF
	GOTO 	END_INT
INT_TMR:
	MOVLW	FREQ
	MOVWF	TMR0
	BCF		INTCON,T0IF
	BTFSS	FLAGS,0
END_INT:
	SWAPF	SAVE_S,W
	MOVWF	STATUS
	SWAPF	SAVE_W,F
	SWAPF	SAVE_W,W
	RETFIE

; Subrotina para delay de 0,5 segundo
DELAY:
	MOVLW	.2
	MOVWF	DL2
LOOP_250MS:
	MOVLW	.250
	MOVWF	DL1
LOOP_1MS:
	MOVLW	.200
	MOVWF	DL0
LOOP:
	NOP
	DECFSZ	DL0,F
	GOTO		LOOP
	DECFSZ	DL1,F
	GOTO		LOOP_1MS
	DECFSZ	DL2,F
	GOTO		LOOP_250MS
	RETURN

; Inicio do programa
INICIO: